version: '3.8'

services:
  youtube-script-ai:
    build: .
    ports:
      - "7860:7860"
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
      - WANDB_API_KEY=${WANDB_API_KEY}
      - ENVIRONMENT=production
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    restart: unless-stopped

  # Optional: Add a database service for future use
  # postgres:
  #   image: postgres:13
  #   environment:
  #     - POSTGRES_DB=youtube_script_ai
  #     - POSTGRES_USER=user
  #     - POSTGRES_PASSWORD=password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data: